// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH3NTTv0PeN_WCuLe2LpPGAbSmwQ9kKBA',
    appId: '1:240272833015:web:d798bf4f799ad74d2456f2',
    messagingSenderId: '240272833015',
    projectId: 'jia634u9099l16jmeaqgasx922n3qh',
    authDomain: 'jia634u9099l16jmeaqgasx922n3qh.firebaseapp.com',
    storageBucket: 'jia634u9099l16jmeaqgasx922n3qh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI2o3k5-Lfn01HvXz-JuGOI7bHnafWkxs',
    appId: '1:240272833015:android:752fc6af117e9a712456f2',
    messagingSenderId: '240272833015',
    projectId: 'jia634u9099l16jmeaqgasx922n3qh',
    storageBucket: 'jia634u9099l16jmeaqgasx922n3qh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrSsqdFmkffYuKhK-KN3GDcjLtg0Oa9b0',
    appId: '1:240272833015:ios:7ff2a3803ca8639f2456f2',
    messagingSenderId: '240272833015',
    projectId: 'jia634u9099l16jmeaqgasx922n3qh',
    storageBucket: 'jia634u9099l16jmeaqgasx922n3qh.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );

}