// Export pages
export '/perfil_login_criar/auth_create/auth_create_widget.dart'
    show AuthCreateWidget;
export '/perfil_login_criar/auth_login/auth_login_widget.dart'
    show AuthLoginWidget;
export '/perfil_login_criar/auth_forgot_password/auth_forgot_password_widget.dart'
    show AuthForgotPasswordWidget;
export '/aa_nav_pages/auth_perfil/auth_perfil_widget.dart'
    show AuthPerfilWidget;
export '/perfil_login_criar/auth_edit_perfil/auth_edit_perfil_widget.dart'
    show AuthEditPerfilWidget;
export '/perfil_login_criar/auth_welcome/auth_welcome_widget.dart'
    show AuthWelcomeWidget;
export '/aa_nav_pages/main_dashboard/main_dashboard_widget.dart'
    show MainDashboardWidget;
export '/messages/chat_details/chat_details_widget.dart' show ChatDetailsWidget;
export '/aa_nav_pages/chat_main/chat_main_widget.dart' show ChatMainWidget;
export '/messages/chat_invite_users/chat_invite_users_widget.dart'
    show ChatInviteUsersWidget;
export '/messages/image_details/image_details_widget.dart'
    show ImageDetailsWidget;
export '/aluno_bilin/perfil_aluno_bilin_criar/perfil_aluno_bilin_criar_widget.dart'
    show PerfilAlunoBilinCriarWidget;
export '/solicitacoes_pais/solicitar_booking_admin/solicitar_booking_admin_widget.dart'
    show SolicitarBookingAdminWidget;
export '/aa_nav_pages/chat_main_admin/chat_main_admin_widget.dart'
    show ChatMainAdminWidget;
export '/localizacao/localizacao_lista/localizacao_lista_widget.dart'
    show LocalizacaoListaWidget;
export '/teacher_availability/availability_list_request/availability_list_request_widget.dart'
    show AvailabilityListRequestWidget;
export '/teacher_availability/available_edit_copy/available_edit_copy_widget.dart'
    show AvailableEditCopyWidget;
export '/teacher_availability/available_edit/available_edit_widget.dart'
    show AvailableEditWidget;
export '/teacher_availability/available_edit_admin/available_edit_admin_widget.dart'
    show AvailableEditAdminWidget;
export '/teacher_availability/available_edit_copy2/available_edit_copy2_widget.dart'
    show AvailableEditCopy2Widget;
export '/aluno_bilin/perfil_aluno_bilin/perfil_aluno_bilin_widget.dart'
    show PerfilAlunoBilinWidget;
export '/registro_aulas_feedback/registro_aulas/registro_aulas_widget.dart'
    show RegistroAulasWidget;
export '/registro_aulas_feedback/registro_aulas_details/registro_aulas_details_widget.dart'
    show RegistroAulasDetailsWidget;
export '/aluno_bilin/perfil_aluno_bilin_edit/perfil_aluno_bilin_edit_widget.dart'
    show PerfilAlunoBilinEditWidget;
export '/notification_permision/notification_permision_widget.dart'
    show NotificationPermisionWidget;
export '/notification_list/notification_list_widget.dart'
    show NotificationListWidget;
export '/notification_form/notification_form_widget.dart'
    show NotificationFormWidget;
