// Sample data for Bilin Tutoring Platform
// Document IDs will be auto-generated by Firestore

final Map<String, List<Map<String, dynamic>>> sampleData = {
  // Users collection - Parents, Teachers, and Admin
  'users': [
    // Parent users
    {
      'role': 'parent',
      'email': 'maria.silva@email.com',
      'phone': '+5547999123456',
      'cpf': '123.456.789-01',
      'name': 'Maria Silva',
      'localizationSettings': {
        'timezone': 'America/Sao_Paulo',
        'language': 'pt-BR',
        'currency': 'BRL'
      },
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'role': 'parent',
      'email': 'carlos.santos@email.com', 
      'phone': '+5547988765432',
      'cpf': '987.654.321-09',
      'name': 'Carlos Santos',
      'localizationSettings': {
        'timezone': 'America/Sao_Paulo',
        'language': 'pt-BR',
        'currency': 'BRL'
      },
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'role': 'parent',
      'email': 'ana.costa@email.com',
      'phone': '+5547977654321',
      'cpf': '456.789.123-45',
      'name': 'Ana Costa',
      'localizationSettings': {
        'timezone': 'America/Sao_Paulo',
        'language': 'pt-BR',
        'currency': 'BRL'
      },
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    // Teacher users
    {
      'role': 'teacher',
      'email': 'sarah.johnson@email.com',
      'phone': '+5547966543210',
      'cpf': '789.123.456-78',
      'name': 'Sarah Johnson',
      'localizationSettings': {
        'timezone': 'America/Sao_Paulo',
        'language': 'en-US',
        'currency': 'BRL'
      },
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'role': 'teacher',
      'email': 'felipe.rodriguez@email.com',
      'phone': '+5547955432109',
      'cpf': '321.654.987-32',
      'name': 'Felipe Rodriguez',
      'localizationSettings': {
        'timezone': 'America/Sao_Paulo',
        'language': 'es-ES',
        'currency': 'BRL'
      },
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'role': 'teacher',
      'email': 'marie.dubois@email.com',
      'phone': '+5547944321098',
      'cpf': '654.987.321-65',
      'name': 'Marie Dubois',
      'localizationSettings': {
        'timezone': 'America/Sao_Paulo',
        'language': 'fr-FR',
        'currency': 'BRL'
      },
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'role': 'teacher',
      'email': 'hans.mueller@email.com',
      'phone': '+5547933210876',
      'cpf': '987.321.654-98',
      'name': 'Hans Mueller',
      'localizationSettings': {
        'timezone': 'America/Sao_Paulo',
        'language': 'de-DE',
        'currency': 'BRL'
      },
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'role': 'parent',
      'email': 'lucia.ferreira@email.com',
      'phone': '+5547922109765',
      'cpf': '258.369.147-25',
      'name': 'Lúcia Ferreira',
      'localizationSettings': {
        'timezone': 'America/Sao_Paulo',
        'language': 'pt-BR',
        'currency': 'BRL'
      },
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'role': 'parent',
      'email': 'roberto.oliveira@email.com',
      'phone': '+5547911098654',
      'cpf': '369.147.258-36',
      'name': 'Roberto Oliveira',
      'localizationSettings': {
        'timezone': 'America/Sao_Paulo',
        'language': 'pt-BR',
        'currency': 'BRL'
      },
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    // Admin user
    {
      'role': 'admin',
      'email': 'admin@bilin.com',
      'phone': '+5547933210987',
      'cpf': '147.258.369-14',
      'name': 'Administrator',
      'localizationSettings': {
        'timezone': 'America/Sao_Paulo',
        'language': 'pt-BR',
        'currency': 'BRL'
      },
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
  ],

  // Students collection
  'students': [
    {
      'name': 'João Silva',
      'birthdate': 'TIMESTAMP', // 8 years old
      'languages': ['English', 'Spanish'],
      'specialNeeds': null,
      'profileImageUrl': null,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'name': 'Camila Silva',
      'birthdate': 'TIMESTAMP', // 12 years old
      'languages': ['English', 'French'],
      'specialNeeds': 'Needs extra patience with pronunciation',
      'profileImageUrl': null,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'name': 'Lucas Santos',
      'birthdate': 'TIMESTAMP', // 10 years old
      'languages': ['English'],
      'specialNeeds': null,
      'profileImageUrl': null,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'name': 'Sofia Costa',
      'birthdate': 'TIMESTAMP', // 9 years old
      'languages': ['English', 'German'],
      'specialNeeds': 'Visual learning style preferred',
      'profileImageUrl': null,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'name': 'Pedro Costa',
      'birthdate': 'TIMESTAMP', // 7 years old
      'languages': ['English'],
      'specialNeeds': null,
      'profileImageUrl': null,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'name': 'Isabella Ferreira',
      'birthdate': 'TIMESTAMP', // 11 years old
      'languages': ['French', 'German'],
      'specialNeeds': 'Prefers interactive learning activities',
      'profileImageUrl': null,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'name': 'Miguel Oliveira',
      'birthdate': 'TIMESTAMP', // 6 years old
      'languages': ['English'],
      'specialNeeds': null,
      'profileImageUrl': null,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'name': 'Gabriela Oliveira',
      'birthdate': 'TIMESTAMP', // 13 years old
      'languages': ['English', 'Spanish'],
      'specialNeeds': 'Advanced student, needs challenging material',
      'profileImageUrl': null,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
  ],

  // Teacher Profiles collection
  'teacherProfiles': [
    {
      'languages': ['English'],
      'experience': 5,
      'hourlyRate': 120.0,
      'isApproved': true,
      'rating': 4.8,
      'totalLessons': 234,
      'certificates': ['TESOL Certificate', 'Bachelor in English Literature'],
      'bio': 'Native English speaker with 5+ years of experience teaching children. Specialized in conversational English and grammar fundamentals.',
      'profileImageUrl': null,
      'educationLevel': ['Bachelor\'s Degree', 'TESOL Certification'],
      'university': 'University of California',
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'languages': ['Spanish', 'English'],
      'experience': 8,
      'hourlyRate': 100.0,
      'isApproved': true,
      'rating': 4.7,
      'totalLessons': 189,
      'certificates': ['Master in Hispanic Literature', 'Teaching Certificate'],
      'bio': 'Bilingual Spanish teacher with extensive experience in language immersion techniques. Focuses on practical conversation skills.',
      'profileImageUrl': null,
      'educationLevel': ['Master\'s Degree', 'Teaching Certificate'],
      'university': 'Universidad Complutense Madrid',
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'languages': ['French', 'English'],
      'experience': 3,
      'hourlyRate': 110.0,
      'isApproved': true,
      'rating': 4.9,
      'totalLessons': 156,
      'certificates': ['DELF Certificate', 'Bachelor in French Studies'],
      'bio': 'French native speaker passionate about sharing language and culture. Uses interactive games and songs to make learning fun.',
      'profileImageUrl': null,
      'educationLevel': ['Bachelor\'s Degree', 'DELF Certification'],
      'university': 'Sorbonne Université',
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'languages': ['German', 'English'],
      'experience': 6,
      'hourlyRate': 95.0,
      'isApproved': true,
      'rating': 4.6,
      'totalLessons': 201,
      'certificates': ['Goethe Certificate', 'Master in Germanic Studies'],
      'bio': 'German teacher with focus on conversational skills and cultural immersion. Specializes in beginner to intermediate levels.',
      'profileImageUrl': null,
      'educationLevel': ['Master\'s Degree', 'Goethe Certification'],
      'university': 'Ludwig-Maximilians-Universität München',
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'languages': ['English'],
      'experience': 2,
      'hourlyRate': 85.0,
      'isApproved': false,
      'rating': 0.0,
      'totalLessons': 0,
      'certificates': ['TEFL Certificate'],
      'bio': 'New teacher eager to help children learn English through creative and engaging methods. Background in elementary education.',
      'profileImageUrl': null,
      'educationLevel': ['Bachelor\'s Degree', 'TEFL Certification'],
      'university': 'University of Cambridge',
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
  ],

  // Locations collection
  'locations': [
    {
      'name': 'Casa da Maria',
      'address': 'Rua das Flores, 123',
      'city': 'Joinville',
      'state': 'SC',
      'zipCode': '89201-000',
      'latitude': -26.3044,
      'longitude': -48.8487,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'name': 'Casa do Carlos',
      'address': 'Av. Beira Rio, 456',
      'city': 'Joinville',
      'state': 'SC', 
      'zipCode': '89202-000',
      'latitude': -26.3122,
      'longitude': -48.8434,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'name': 'Residência Ana Costa',
      'address': 'Rua do Príncipe, 789',
      'city': 'Joinville',
      'state': 'SC',
      'zipCode': '89203-000',
      'latitude': -26.2989,
      'longitude': -48.8567,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'name': 'Biblioteca Central',
      'address': 'Rua XV de Novembro, 200',
      'city': 'Joinville',
      'state': 'SC',
      'zipCode': '89201-400',
      'latitude': -26.3051,
      'longitude': -48.8398,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
  ],

  // Lessons collection
  'lessons': [
    {
      'scheduledTime': 'TIMESTAMP', // Next Monday 10:00 AM
      'duration': 60,
      'language': 'English',
      'status': 'scheduled',
      'parentNote': 'João is excited to practice conversation',
      'price': 120.0,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'scheduledTime': 'TIMESTAMP', // Last week
      'duration': 90,
      'language': 'French',
      'status': 'completed',
      'parentNote': 'Focus on pronunciation please',
      'price': 165.0,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'scheduledTime': 'TIMESTAMP', // Tomorrow 2:00 PM
      'duration': 60,
      'language': 'English',
      'status': 'scheduled',
      'parentNote': null,
      'price': 120.0,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'scheduledTime': 'TIMESTAMP', // Yesterday
      'duration': 60,
      'language': 'Spanish',
      'status': 'completed',
      'parentNote': 'Lucas wants to learn about animals',
      'price': 100.0,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
  ],

  // Payments collection
  'payments': [
    {
      'amount': 165.0,
      'status': 'completed',
      'method': 'pix',
      'paidAt': 'TIMESTAMP',
      'transactionId': 'PIX123456789',
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'amount': 120.0,
      'status': 'pending',
      'method': 'pix',
      'paidAt': null,
      'transactionId': null,
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'amount': 100.0,
      'status': 'completed',
      'method': 'card',
      'paidAt': 'TIMESTAMP',
      'transactionId': 'CARD987654321',
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
  ],

  // Progress Reports collection
  'progressReports': [
    {
      'attendance': 'Present',
      'participation': 'Excellent',
      'comprehension': 'Good',
      'speaking': 'Fair',
      'topicsCovered': 'Colors, numbers 1-20, basic greetings, family members',
      'homework': 'Practice counting to 20, review color flashcards',
      'nextLessonPlan': 'Continue with basic vocabulary, introduce simple sentences',
      'attachments': null,
      'createdAt': 'TIMESTAMP',
    },
    {
      'attendance': 'Present',
      'participation': 'Good',
      'comprehension': 'Excellent',
      'speaking': 'Good',
      'topicsCovered': 'Past tense verbs, telling time, daily routines',
      'homework': 'Write 5 sentences using past tense, practice time exercises',
      'nextLessonPlan': 'Review past tense, introduce future tense concepts',
      'attachments': null,
      'createdAt': 'TIMESTAMP',
    },
  ],

  // Teacher Availability collection
  'teacherAvailability': [
    {
      'weeklyAvailability': [
        {
          'dayOfWeek': 1, // Monday
          'startTime': '09:00',
          'endTime': '17:00',
          'isAvailable': true,
        },
        {
          'dayOfWeek': 2, // Tuesday
          'startTime': '09:00',
          'endTime': '17:00',
          'isAvailable': true,
        },
        {
          'dayOfWeek': 3, // Wednesday
          'startTime': '09:00',
          'endTime': '17:00',
          'isAvailable': true,
        },
        {
          'dayOfWeek': 4, // Thursday
          'startTime': '09:00',
          'endTime': '17:00',
          'isAvailable': true,
        },
        {
          'dayOfWeek': 5, // Friday
          'startTime': '09:00',
          'endTime': '12:00',
          'isAvailable': true,
        },
        {
          'dayOfWeek': 6, // Saturday
          'startTime': '09:00',
          'endTime': '15:00',
          'isAvailable': false,
        },
        {
          'dayOfWeek': 0, // Sunday
          'startTime': '10:00',
          'endTime': '14:00',
          'isAvailable': false,
        },
      ],
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
    {
      'weeklyAvailability': [
        {
          'dayOfWeek': 1, // Monday
          'startTime': '08:00',
          'endTime': '18:00',
          'isAvailable': true,
        },
        {
          'dayOfWeek': 2, // Tuesday
          'startTime': '08:00',
          'endTime': '18:00',
          'isAvailable': true,
        },
        {
          'dayOfWeek': 3, // Wednesday
          'startTime': '14:00',
          'endTime': '20:00',
          'isAvailable': true,
        },
        {
          'dayOfWeek': 4, // Thursday
          'startTime': '08:00',
          'endTime': '18:00',
          'isAvailable': true,
        },
        {
          'dayOfWeek': 5, // Friday
          'startTime': '08:00',
          'endTime': '18:00',
          'isAvailable': true,
        },
        {
          'dayOfWeek': 6, // Saturday
          'startTime': '09:00',
          'endTime': '16:00',
          'isAvailable': true,
        },
        {
          'dayOfWeek': 0, // Sunday
          'startTime': '10:00',
          'endTime': '16:00',
          'isAvailable': false,
        },
      ],
      'createdAt': 'TIMESTAMP',
      'updatedAt': 'TIMESTAMP',
    },
  ],
};